version: '3'
services:
  etcd-node1:
    image: quay.io/coreos/etcd
    container_name: etcd-node1
    ports:
      - '2379:2379'
      - '2380:2380'
    command: etcd -name etcd-node1 -advertise-client-urls http://0.0.0.0:2379 -listen-client-urls http://0.0.0.0:2379 -listen-peer-urls http://0.0.0.0:2380  -initial-cluster-token etcd-cluster -initial-cluster "etcd-node1=http://etcd-node1:2380,etcd-node2=http://etcd-node2:2380,etcd-node3=http://etcd-node3:2380" -initial-cluster-state new
    networks:
      - 'etcd'
    volumes:
      - ../data/etcd/etcd1:/opt/etcd/data
    environment:
      - 'ETCD_DATA_DIR=/opt/etcd/data'

  etcd-node2:
    image: quay.io/coreos/etcd
    container_name: etcd-node2
    ports:
      - '23792:2379'
      - '23802:2380'
    command: etcd -name etcd-node2 -advertise-client-urls http://0.0.0.0:2379 -listen-client-urls http://0.0.0.0:2379 -listen-peer-urls http://0.0.0.0:2380 -initial-cluster-token etcd-cluster -initial-cluster "etcd-node1=http://etcd-node1:2380,etcd-node2=http://etcd-node2:2380,etcd-node3=http://etcd-node3:2380" -initial-cluster-state new
    networks:
      - 'etcd'
    volumes:
      - ../data/etcd/etcd2:/opt/etcd/data
    environment:
      - 'ETCD_DATA_DIR=/opt/etcd/data'

  etcd-node3:
    image: quay.io/coreos/etcd
    container_name: etcd-node3
    ports:
      - '23793:2379'
      - '23803:2380'
    command: etcd -name etcd-node3 -advertise-client-urls http://0.0.0.0:2379 -listen-client-urls http://0.0.0.0:2379 -listen-peer-urls http://0.0.0.0:2380 -initial-cluster-token etcd-cluster -initial-cluster "etcd-node1=http://etcd-node1:2380,etcd-node2=http://etcd-node2:2380,etcd-node3=http://etcd-node3:2380" -initial-cluster-state new
    networks:
      - 'etcd'
    volumes:
      - ../data/etcd/etcd3:/opt/etcd/data
    environment:
      - 'ETCD_DATA_DIR=/opt/etcd/data'
  # e3w:
  #   hostname: e3w
  #   image: soyking/e3w:latest
  #   deploy:
  #     replicas: 1
  #     restart_policy:
  #       condition: on-failure
  #       max_attempts: 3
  #   ports:
  #     - '23791:8080'
  #   volumes:
  #     - ./data/e3w/conf/config/conf.ini:/app/conf/config.default.ini
  #   networks:
  #     - etcd

  etcd-keeper:
    image: 'evildecay/etcdkeeper'
    container_name: 'etcd-keeper'
    ports:
      - '23791:8080'
    networks:
      - 'etcd'

networks:
  etcd:
